
import { Product, Supplier } from './types';

export const CATEGORIES = [
  "Electronics", "Groceries", "Apparel", "Home Decor", "Health & Beauty", "Automotive", "Stationery"
];

export const MOCK_SUPPLIERS: Supplier[] = [
  { id: 's1', name: 'Global Tech Solutions', rating: 4.8, verified: true, location: 'Industrial Area, Phase II', distance: '2.4 km', categories: ['Electronics'] },
  { id: 's2', name: 'FreshMart Wholesale', rating: 4.5, verified: true, location: 'Market Yard', distance: '1.2 km', categories: ['Groceries'] },
  { id: 's3', name: 'Urban Threads Ltd', rating: 4.2, verified: false, location: 'Fashion Hub', distance: '5.6 km', categories: ['Apparel'] },
  { id: 's4', name: 'Home Essentials Co.', rating: 4.7, verified: true, location: 'Downtown', distance: '3.1 km', categories: ['Home Decor'] },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Wireless Bluetooth Headphones Pro',
    category: 'Electronics',
    price: 1200,
    mrp: 2500,
    discount: 52,
    rating: 4.5,
    reviews: 120,
    image: 'https://picsum.photos/seed/headphones/400/300',
    supplierId: 's1',
    supplierName: 'Global Tech Solutions',
    supplierPhone: '+91 98765 43210',
    supplierEmail: 'sales@globaltech.com',
    minOrderQty: 5,
    stock: 200,
    description: 'High-quality sound with noise cancellation. Perfect for resale.',
    distance: '2.4 km',
    isTrending: true,
    sku: 'EL-AUD-1029',
    mfgDate: '2024-01-15'
  },
  {
    id: 'p2',
    name: 'Premium Organic Basmati Rice 5kg',
    category: 'Groceries',
    price: 450,
    mrp: 600,
    discount: 25,
    rating: 4.8,
    reviews: 850,
    image: 'https://picsum.photos/seed/rice/400/300',
    supplierId: 's2',
    supplierName: 'FreshMart Wholesale',
    supplierPhone: '+91 91234 56789',
    supplierEmail: 'bulk@freshmart.in',
    minOrderQty: 10,
    stock: 500,
    description: 'A-grade long grain rice sourced directly from farmers.',
    distance: '1.2 km',
    isTrending: true,
    sku: 'GR-RIC-5002',
    mfgDate: '2023-11-20',
    expiryDate: '2025-11-20'
  },
  {
    id: 'p3',
    name: 'Cotton Men\'s Slim Fit Shirt',
    category: 'Apparel',
    price: 350,
    mrp: 899,
    discount: 61,
    rating: 4.1,
    reviews: 45,
    image: 'https://picsum.photos/seed/shirt/400/300',
    supplierId: 's3',
    supplierName: 'Urban Threads Ltd',
    supplierPhone: '+91 88877 66554',
    supplierEmail: 'orders@urbanthreads.com',
    minOrderQty: 12,
    stock: 100,
    description: 'Breathable fabric available in multiple colors and sizes.',
    distance: '5.6 km',
    sku: 'AP-SHR-4410',
    mfgDate: '2024-02-01'
  },
  {
    id: 'p4',
    name: 'Modern Ceramic Flower Vase',
    category: 'Home Decor',
    price: 250,
    mrp: 499,
    discount: 50,
    rating: 4.6,
    reviews: 32,
    image: 'https://picsum.photos/seed/vase/400/300',
    supplierId: 's4',
    supplierName: 'Home Essentials Co.',
    supplierPhone: '+91 77766 55443',
    supplierEmail: 'contact@homeessentials.co',
    minOrderQty: 2,
    stock: 50,
    description: 'Minimalist design for modern interiors.',
    distance: '3.1 km',
    sku: 'HD-VAS-2291',
    mfgDate: '2023-12-10'
  },
  {
    id: 'p5',
    name: 'Smart LED Bulb 12W',
    category: 'Electronics',
    price: 180,
    mrp: 350,
    discount: 48,
    rating: 4.3,
    reviews: 210,
    image: 'https://picsum.photos/seed/bulb/400/300',
    supplierId: 's1',
    supplierName: 'Global Tech Solutions',
    supplierPhone: '+91 98765 43210',
    supplierEmail: 'sales@globaltech.com',
    minOrderQty: 20,
    stock: 1000,
    description: 'Energy-efficient smart lighting with app control.',
    distance: '2.4 km',
    isTrending: true,
    sku: 'EL-LGT-8821',
    mfgDate: '2024-03-05'
  },
  {
    id: 'p6',
    name: 'Stainless Steel Water Bottle 1L',
    category: 'Home Decor',
    price: 120,
    mrp: 299,
    discount: 60,
    rating: 4.4,
    reviews: 88,
    image: 'https://picsum.photos/seed/bottle/400/300',
    supplierId: 's4',
    supplierName: 'Home Essentials Co.',
    supplierPhone: '+91 77766 55443',
    supplierEmail: 'contact@homeessentials.co',
    minOrderQty: 10,
    stock: 300,
    description: 'BPA-free durable eco-friendly bottle.',
    distance: '3.1 km',
    sku: 'HD-BOT-1104',
    mfgDate: '2024-01-20'
  }
];
